### ISSUE TITLE
500 error when using `yarn` extension

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#1483] opened 2024-08-29 14:05 UTC
# Overview
This is submitted from a Community Edition user.

> $ rm -rf node_modules/
$ phylum auth login
Please use browser window to complete login process
If browser window doesn't open, you can use the link below:
   https://login.phylum.io/realms/phylum/protocol/openid-connect/auth?client_id=locksmith&code_challenge=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&code_challenge_method=S256&redirect_uri=http%3A%2F%2F127.0.0.1%3A40487%2F&response_type=code&response_mode=query&scope=openid+offline_access&state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
✅ User login successful
$ phylum yarn install
[phylum] Updating lockfile…
➤ YN0000: · Yarn 4.4.1
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ ethers is listed by your project with version 5.7.2 (p380c2), which doesn't satisfy what @typechain/hardhat and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ typechain is listed by your project with version 5.2.0 (p0304d), which doesn't satisfy what @typechain/hardhat and other dependencies request (but they have non-overlapping ranges!).
➤ YN0002: │ polkastarter-token-sale@workspace:. doesn't provide @typechain/ethers-v6 (p55d24), requested by @typechain/hardhat.
➤ YN0002: │ polkastarter-token-sale@workspace:. doesn't provide @types/sinon-chai (p58a9e), requested by @nomiclabs/hardhat-waffle.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0073: │ Skipped due to mode=update-lockfile
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 196ms
[phylum] Lockfile updated successfully.
[phylum] Analyzing packages…
Extension error: Uncaught (in promise) Error: HTTP request error (500 Internal Server Error):
an internal error has occured
  const result = await Phylum.checkPackagesRaw(lockfile.packages);
                 ^
    at async checkDryRun (file:///home/sum/.local/share/phylum/extensions/yarn/main.ts:212:18)
    at async file:///home/sum/.local/share/phylum/extensions/yarn/main.ts:100:3

# Additional Context
I will send the associated files internally.

**Comment by cd-work** [comment] 2024-08-29 14:07
Sporadic 500 errors definitely happen occasionally. Did we confirm that this was not just sporadic?

**Comment by furi0us333** [comment] 2024-08-29 15:20
I did not, but I can. Comms are slow, so it might be a 24 hour turn around time on the response.

**Comment by kylewillmon** [comment] 2024-08-29 16:03
I have reproduced this locally and can confirm that this appears to be an API bug.

It seems like something about these dependencies is causing issues when run through policy... And specifically only with `/api/v0/packages/check/raw` because `phylum analyze` works just fine...

I will open an API issue shortly.

**Comment by kylewillmon** [comment] 2024-08-29 16:55
It looks like this is being caused by a duplicate entry in the lockfile. Here is a minimal example reproduced with `curl`:

```
> curl -s -H "Authorization: $(phylum auth token)" -X POST -d '[{"name": "fsevents", "version": "2.3.3", "type": "npm"}, {"name": "fsevents", "version": "2.3.3", "type": "npm"}]' 'https://api.staging.phylum.io/api/v0/data/packages/check/raw'
{
  "error": {
    "error_id": "00-01327e51a9d0ad0475a8446db0ea479e-25fbbba9c8b2d23a-01",
    "code": 500,
    "reason": "Internal Server Error",
    "apiError": {
      "type": "InternalServiceError"
    },
    "description": "an internal error has occured"
  }
}                                                                                                                                                                                                                                                                                                                               
```

In this case, the reason for the duplicate entry in the lockfile seems to be related to a yarn package patching. But it definitely shouldn't be causing a 500 error.

**Comment by SvenMeyer** [comment] 2024-09-05 14:59
I would like this to be high priority.
How otherwise safely install (all) packages with yarn (which "quite a few" developers are using) ?

**Comment by SvenMeyer** [comment] 2024-09-05 15:02
Would `yarn dedupe` be a (fast to implement ?) option ?

https://yarnpkg.com/cli/dedupe

yarn dedupe --strategy highest

Just include that call before doing the `phylum analyze` part ?

(That is likely slower than having Phylum ignore double entries, but a) its easy to implement, b) also makes the whole package smaller)

**Comment by matt-phylum** [comment] 2024-09-05 16:52
dedupe sounds like it does something different. It's not a problem if multiple versions of the same package are present.

**Comment by maxrake** [comment] 2024-09-05 18:12
> I would like this to be high priority.

There is a fix in review now (for a private Phylum API repository). We hope to get this out quickly.

**Comment by kylewillmon** [comment] 2024-09-06 13:59
> How otherwise safely install (all) packages with yarn

This bug currently only impacts `phylum yarn`. It is still possible to safely analyze the dependencies of any yarn project with [this command](https://docs.phylum.io/cli/commands/phylum_analyze):

```
phylum analyze yarn.lock
```

Additionally, our customers can use the [Phylum GitHub App](https://docs.phylum.io/integrations/github_app) and our [other integrations](https://docs.phylum.io/integrations/integrations_overview) to protect their projects.

**Comment by maxrake** [comment] 2024-09-11 20:11
The fix worked. Closing this issue...

**Closed by maxrake** 2024-09-11 20:11 UTC
Labels: bug, low priority, extensions
