### ISSUE TITLE
Odd lines in `help` output

### ISSUE THREAD

**Issue by furi0us333** [phylum-dev/cli#808] opened 2022-11-14 15:05 UTC
# Overview
The `help` output yields strange lines and ellipses in the help text.

# How To Reproduce
Steps to reproduce this behavior:
1. Run `ph help auth`
2. See error

# Expected Behavior
Unexpected lines and ellipses are not present.

# Additional Context
Win10 WSL
Phylum v3.12.1

![image](https://user-images.githubusercontent.com/34108612/201692789-c10e0b53-a6f4-4d13-ad53-b0d2f27fc63e.png)

**Comment by cd-work** [comment] 2022-11-14 15:14
What do you find odd about the ellipses? They seem to be working as intended.

As for the lines, I can't reproduce it on Linux. @kylewillmon / @andreaphylum / @maxrake can you reproduce on macOS?

**Comment by cd-work** [comment] 2022-11-14 15:15
@furi0us333 Oh out of curiosity: Which terminal are you using? I feel like it might be incorrectly dealing with a clear line right before the line is written when the previous line's underline sgr attribute is still set.

**Comment by kylewillmon** [comment] 2022-11-14 15:18
> What do you find odd about the ellipses? They seem to be working as intended.

To clarify for @furi0us333:

```
  -q, --quiet...    Reduce the level of verbosity (the maximum is -qq)
  -v, --verbose...  Increase the level of verbosity (the maximum is -vvv)
```

The ellipses are there to indicate that `-q` and `-v` can be supplied many times. This is common practice for command-line applications.

**Comment by cd-work** [comment] 2022-11-14 15:20
If you run `printf "\e[41;4mTEST\e[0K\n"` and you get a line that is completely underlined, your terminal is broken.

It should print an underlined "TEST" and the entire line should be red.

**Comment by maxrake** [comment] 2022-11-14 16:17
I also could not reproduce on zsh and macOS:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/18729796/201710548-2d6b1f4b-10d6-478c-90fe-79e43d958708.png">

**Comment by andreaphylum** [comment] 2022-11-14 16:23
I also could not reproduce on OS X. FWIW, Windows Terminal does have a handful of rendering quirks similar to this.

**Comment by furi0us333** [comment] 2022-11-14 16:24
> > What do you find odd about the ellipses? They seem to be working as intended.
> 
> To clarify for @furi0us333:
> 
> ```
>   -q, --quiet...    Reduce the level of verbosity (the maximum is -qq)
>   -v, --verbose...  Increase the level of verbosity (the maximum is -vvv)
> ```
> 
> The ellipses are there to indicate that `-q` and `-v` can be supplied many times. This is common practice for command-line applications.

Understood - my mistake on that one. The lines might just be a WSL thing.

**Comment by cd-work** [comment] 2022-11-14 16:43
Yeah more specifically this is an issue with the terminal you're running WSL in.

@furi0us333 Does that mean this issue can be discarded? Or would you still want to bring it up with clap. Since technically the emission of a `\e[0m` after the underline text should still fix it for broken terminals.

**Comment by furi0us333** [comment] 2022-11-14 16:48
I closed and re-opened my terminal and the Phylum text seems to be rendering ok now. I still get the full red underline, but it doesn't seem to be messing up Phylum anymore, so I think we can close this as just something weird on my end. Thanks.

![image](https://user-images.githubusercontent.com/34108612/201717682-b57228ee-8b52-49e2-9264-9a305e656c8d.png)

**Comment by kylewillmon** [comment] 2022-11-14 17:19
> Looks like I am still running the 'ole Windows conhost

I highly recommend that you switch to [Windows Terminal](https://aka.ms/terminal) (which is available for Windows 10 and [the default](https://devblogs.microsoft.com/commandline/windows-terminal-is-now-the-default-in-windows-11/) on Windows 11). I expect that will fix this issue.

In any case, since the issue was fixed by restarting the terminal, I do not think we need to do anything further on this issue.

**Closed by kylewillmon** 2022-11-14 17:19 UTC
Labels: bug
