### ISSUE TITLE
Python non-standard locations

### ISSUE THREAD

**Issue by ejortega** [phylum-dev/cli#151] opened 2021-12-15 05:32 UTC
**Describe the issue**
The PyPI parser currently strips out non-standard locations when parsing pip requirements.

**Describe why the issue is needed**
We need to be able to send all non-standard locations for processing

**Describe the proposed solution**
Modify the pypi parser https://github.com/phylum-dev/cli/blob/724395d036bc56c69acd69c0f59ea1308350a2c1/lib/src/lockfiles/parsers.rs#L157 to return non-standard locations. Examples and standards can be found https://pip.pypa.io/en/stable/user_guide/#resolver-changes-2020

**Estimated Subtasks**
Update parser
Might require updates to PyPI downloader and processor

**Comment by kylewillmon** [comment] 2022-04-25 20:16
Duplicate of #94 and similarly resolved.

**Closed by kylewillmon** 2022-04-25 20:16 UTC
Labels: enhancement, task
